name: nlp-exercises-main
channels:
  - conda-forge
  - intel
dependencies:
  - python
  - pip
  - nb_conda_kernels
  - matplotlib
  - nltk
  - seaborn
  - scikit-learn
  - scipy=1.12
  - datasets
  - jax=0.4.23
  - flax
  - equinox
  - optax
  - pytorch
  - scikit-multilearn
  - umap-learn
  - pandas
  - datashader
  - bokeh
  - holoviews
  - colorcet
  - scikit-image
  - adjusttext
  - pympler
  - gensim
  - ai2-olmo
  - intel_extension_for_transformers
  - ipympl
  - jedi-language-server
  - jupyterlab-lsp
  - jupyter-resource-usage
  - sentence-transformers
  - transformers
  - accelerate
  - llama-cpp-python
  - otter-grader
  - tabulate
  - openai
  - pip:
    - textalloc
