name: nlp-exercises-main
channels:
  - conda-forge
  - intel
dependencies:
  - nb_conda_kernels
  - matplotlib
  - nltk
  - seaborn
  - scikit-learn
  - datasets
  - jax=0.4.23
  - equinox
  - optax
  - pytorch
  - scikit-multilearn
  - umap-learn
  - pandas
  - datashader
  - bokeh
  - holoviews
  - colorcet
  - scikit-image
  - adjusttext
  - pympler
  - gensim
  - ai2-olmo
  - intel_extension_for_transformers
  - ipympl
