name: nlp-exercises-main
channels:
  - conda-forge
dependencies:
  - nb_conda_kernels
  - matplotlib
  - nltk
  - seaborn
  - scikit-learn
  - datasets
  - jax=0.4.23
  - equinox
  - optax
  - pytorch
