name: Docker

on:
  push:
  pull_request:

jobs:
  build_publish_containers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build/push
        uses: whoan/docker-build-with-cache-action@v8
        with:
          registry: ghcr.io
          image_name: frankier/nlp-exercises-notebook
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
